package alert

import (
	"time"

	"github.com/google/uuid"
)

// Alert represents an alert instance generated by the system.
type Alert struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	RuleID     uuid.UUID
	IncidentID uuid.UUID
	Severity   string
	Status     AlertStatus
	Message    string
	Deliveries []uuid.UUID // AlertDelivery IDs
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AlertStatus string

const (
	AlertStatusPending    AlertStatus = "pending"
	AlertStatusSent       AlertStatus = "sent"
	AlertStatusDelivered  AlertStatus = "delivered"
	AlertStatusFailed     AlertStatus = "failed"
	AlertStatusSuppressed AlertStatus = "suppressed"
)
