package alert

import (
	"time"
)

// Alert represents an alert instance generated by the system.
type Alert struct {
	ID         string
	TenantID   string
	RuleID     string
	IncidentID string
	Severity   string
	Status     AlertStatus
	Message    string
	Deliveries []string // AlertDelivery IDs
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AlertStatus string

const (
	AlertStatusPending    AlertStatus = "pending"
	AlertStatusSent       AlertStatus = "sent"
	AlertStatusDelivered  AlertStatus = "delivered"
	AlertStatusFailed     AlertStatus = "failed"
	AlertStatusSuppressed AlertStatus = "suppressed"
)
